### ISSUE TITLE
wygenerowanie przykładowych danych do bazy

### ISSUE THREAD

**Issue by kkrolikowski** [kkrolikowski/pubcloudtest#2]
Przykładowe dane posłużą jako punkt odniesienia do wypełnienia bazy losowymi danymi.

**Comment by cathy1721** [comment]
przykładowe dane - przynajmniej jeden rekord per tabelka.
Do zrobienia: sprawdzić spójność danych (dodać klucze)

**Comment by cathy1721** [comment]
done
